const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Peaceful mountain cabin surrounded by nature.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Luxury Villa with Pool",
    description: "Enjoy luxury living with a private pool and stunning views.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 3000,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Desert Safari Camp",
    description: "Experience the desert with this unique stay under the stars.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 800,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Lakeview Cabin",
    description: "Relax in a cozy cabin with breathtaking lake views.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 1100,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Treehouse Adventure",
    description: "Stay in a magical treehouse surrounded by forest.",
    image: "https://images.unsplash.com/photo-1475855581690-80accde3ae2b",
    price: 900,
    location: "Kerala",
    country: "India",
  },
  {
    title: "City Studio Apartment",
    description: "Compact and comfortable studio in a busy city area.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    price: 700,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Snowy Chalet",
    description: "Perfect winter getaway in a snowy chalet.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 2000,
    location: "Manali",
    country: "India",
  },
  {
    title: "Island Beach Hut",
    description: "Simple beach hut right on the island shore.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 600,
    location: "Goa",
    country: "India",
  }
];

module.exports = { sampleListings };